# Hardcoded mappings for Manning Charts
# Generated from Excel files to remove runtime dependency

SOUTHSIDE_MAPPING = {'am action station': 'ACTION',
 'am beverage/floor': 'BEVERAGE/FLOOR',
 'am cashier': 'CASHIER',
 'am deli': 'DELI',
 'am deli student': 'DELI',
 'am deli student 1': 'DELI',
 'am dessert': 'BLUE RIDGE BAKERY',
 'am dessert student': 'BLUE RIDGE BAKERY',
 'am dwo': 'DELICIOUS WITHOUT',
 'am dwo 1': 'DELICIOUS WITHOUT',
 'am dwo 2': 'DELICIOUS WITHOUT',
 'am dwo student': 'DELICIOUS WITHOUT',
 'am dwo student 1': 'DELICIOUS WITHOUT',
 'am dwo student 2': 'DELICIOUS WITHOUT',
 'am grill': 'PATRIOT PIT',
 'am grill 1': 'PATRIOT PIT',
 'am grill 2': 'PATRIOT PIT',
 'am mason manor': 'MASON MANOR',
 'am mason manor 1': 'MASON MANOR',
 'am mason manor 2': 'MASON MANOR',
 'am mason manor student': 'MASON MANOR',
 'am pasta student': 'LITTLE ITALY',
 'am pasta student 1': 'LITTLE ITALY',
 'am pizza': 'POTOMAC PIE',
 'am pizza 1': 'POTOMAC PIE',
 'am pizza student': 'POTOMAC PIE',
 'am prep': 'CULINARY',
 'am production': 'CULINARY',
 'am production 1': 'CULINARY',
 'am production 2': 'CULINARY',
 'am production 3': 'CULINARY',
 'am receiver': 'RECEIVER',
 'am salad bar': 'SALAD BAR',
 'am salad bar student': 'SALAD BAR',
 'am supervisor': 'SUPERVISOR',
 'am table busser (student)': 'TABLE BUSSER',
 'am utility': 'DISHROOM',
 'am utility (table busser)': 'TABLE BUSSER',
 'am utility 1': 'DISHROOM',
 'am utility 2': 'DISHROOM',
 'am utility student': 'DISHROOM',
 'avoiding gluten': 'AVOIDING GLUTEN',
 'cashier student': 'CASHIER',
 'cdc': 'CHILD CARE',
 'culinary supervisor': 'SUPERVISOR',
 'mason club': 'MASON CLUB',
 'mid cashier': 'CASHIER',
 'mid grill': 'PATRIOT PIT',
 'mid prep': 'CULINARY',
 'mid production': 'CULINARY',
 'mid utility': 'DISHROOM',
 'mid utility student': 'DISHROOM',
 'mid utility student 1': 'DISHROOM',
 'mid utility student 2': 'DISHROOM',
 'pm cashier': 'CASHIER',
 'pm deli': 'DELI',
 'pm deli student': 'DELI',
 'pm dessert': 'BLUE RIDGE BAKERY',
 'pm dessert student': 'BLUE RIDGE BAKERY',
 'pm dwo': 'DELICIOUS WITHOUT',
 'pm dwo 1': 'DELICIOUS WITHOUT',
 'pm dwo 2': 'DELICIOUS WITHOUT',
 'pm dwo student': 'DELICIOUS WITHOUT',
 'pm dwo student 1': 'DELICIOUS WITHOUT',
 'pm grill': 'PATRIOT PIT',
 'pm grill student': 'PATRIOT PIT',
 'pm mason manor': 'MASON MANOR',
 'pm mason manor student': 'MASON MANOR',
 'pm pasta': 'LITTLE ITALY',
 'pm pasta student': 'LITTLE ITALY',
 'pm pizza': 'POTOMAC PIE',
 'pm pizza student': 'POTOMAC PIE',
 'pm prep': 'CULINARY',
 'pm production': 'CULINARY',
 'pm salad bar': 'SALAD BAR',
 'pm salad bar student': 'SALAD BAR',
 'pm supervisor': 'SUPERVISOR',
 'pm table busser (student)': 'TABLE BUSSER',
 'pm utility': 'DISHROOM',
 'pm utility (table busser)': 'TABLE BUSSER',
 'pm utility student': 'DISHROOM',
 'pm utility student 1': 'DISHROOM',
 'student admin': 'STUDENT ADMIN'}

IKES_MAPPING = {'cashier am': 'CASHIER',
 'cashier ovnt': 'CASHIER',
 'cashier pm': 'CASHIER',
 'cold prep  pm 2': 'SALAD BAR',
 'cold prep cook am': 'SALAD BAR',
 'cold prep cook pm': 'SALAD BAR',
 'deli cook am': 'HOMESLICE',
 'dwo cook am': 'DELICIOUS WITHOUT',
 'dwo cook pm1': 'DELICIOUS WITHOUT',
 'dwo cook pm2': 'DELICIOUS WITHOUT',
 'flips cook am1': 'GRILL',
 'flips cook am2': 'GRILL',
 'flips cook am3': 'GRILL',
 'flips cook ovnt': 'GRILL',
 'flips cook pm1': 'GRILL',
 'flips cook pm2': 'GRILL',
 'flips cook pm3': 'GRILL',
 'flips cook pm4': 'GRILL',
 'none': 'NONE',
 'pizza cook am': 'PIZZA',
 'pizza cook pm': 'PIZZA',
 'production cook am1': 'HOMESTYLE',
 'production cook am2': 'HOMESTYLE',
 'production cook am3': 'HOMESTYLE',
 'production cook pm1': 'HOMESTYLE',
 'production cook pm2': 'HOMESTYLE',
 'production cook pm3': 'HOMESTYLE',
 'receiver am1': 'RECEIVER',
 'receiver am2': 'RECEIVER',
 'student admin': 'STUDENT ADMIN',
 'student desserts am1': 'DESSERTS',
 'student desserts am2': 'DESSERTS',
 'student desserts pm1': 'DESSERTS',
 'student desserts pm2': 'DESSERTS',
 'student dwo am1': 'DELICIOUS WITHOUT',
 'student dwo am2': 'DELICIOUS WITHOUT',
 'student dwo pm1': 'DELICIOUS WITHOUT',
 'student dwo pm2': 'DELICIOUS WITHOUT',
 'student flips ovnt': 'GRILL',
 'student foh ovnt1': 'UTILITY FOH',
 'student foh ovnt2': 'UTILITY FOH',
 'student foh pm': 'UTILITY FOH',
 'student homeslice am': 'HOMESLICE',
 'student homeslice pm1': 'HOMESLICE',
 'student homeslice pm2': 'HOMESLICE',
 'student homestyle am1': 'HOMESTYLE',
 'student homestyle am2': 'HOMESTYLE',
 'student homestyle pm1': 'HOMESTYLE',
 'student homestyle pm2': 'HOMESTYLE',
 'student pizza/pasta am': 'PIZZA',
 'student pizza/pasta ovnt': 'PIZZA',
 'student pizza/pasta pm': 'PIZZA',
 'student salad bar am1': 'SALAD BAR',
 'student salad bar am2': 'SALAD BAR',
 'student salad bar pm1': 'SALAD BAR',
 'student salad bar pm2': 'SALAD BAR',
 'student supervisor': 'SUPERVISOR',
 'student united table am1': 'UNITED TABLE',
 'student united table am2': 'UNITED TABLE',
 'student united table pm': 'UNITED TABLE',
 'student utility am1': 'UTILITY DISHROOM',
 'student utility am2': 'UTILITY DISHROOM',
 'student utility am3': 'UTILITY DISHROOM',
 'student utility am4': 'UTILITY DISHROOM',
 'student utility am5': 'UTILITY DISHROOM',
 'student utility ovnt1': 'UTILITY DISHROOM',
 'student utility ovnt2': 'UTILITY DISHROOM',
 'student utility pm1': 'UTILITY DISHROOM',
 'student utility pm2': 'UTILITY DISHROOM',
 'student utility pm3': 'UTILITY DISHROOM',
 'student utility pm4': 'UTILITY DISHROOM',
 'student utility pm5': 'UTILITY DISHROOM',
 'student utility pm6': 'UTILITY DISHROOM',
 'student utility pm7': 'UTILITY DISHROOM',
 'student utility pm8': 'UTILITY DISHROOM',
 'supervisor am': 'SUPERVISOR',
 'supervisor ovnt': 'SUPERVISOR',
 'supervisor pm1': 'SUPERVISOR',
 'supervisor pm2': 'SUPERVISOR',
 'united table cook am': 'UNITED TABLE',
 'united table cook pm1': 'UNITED TABLE',
 'united table cook pm2': 'UNITED TABLE',
 'utility dishroom  flex': 'UTILITY DISHROOM',
 'utility dishroom am1': 'UTILITY DISHROOM',
 'utility dishroom am2': 'UTILITY DISHROOM',
 'utility dishroom am3': 'UTILITY DISHROOM',
 'utility dishroom am4': 'UTILITY DISHROOM',
 'utility dishroom ovnt': 'UTILITY DISHROOM',
 'utility dishroom pm1': 'UTILITY DISHROOM',
 'utility dishroom pm2': 'UTILITY DISHROOM',
 'utility foh am1': 'UTILITY FOH',
 'utility foh am2': 'UTILITY FOH',
 'utility foh ovnt': 'UTILITY FOH',
 'utility foh pm': 'UTILITY FOH',
 'utility pots am': 'UTILITY POTS',
 'utility pots pm': 'UTILITY POTS'}
